local:
  SECRET_KEY: uw*@o9*-$v3-gqlqrnqoxc1rym1sspat92k3_wgjb$6i-2d2!$
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: db.sqlite3

development:
  SECRET_KEY: uw*@o9*-$v3-gqlqrnqoxc1rym1sspat92k3_wgjb$6i-2d2!$
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: db.sqlite3

production:
  SECRET_KEY: django-insecure-xgq(nak%w#q$1k_kii+0k3i5zh*q4xx9xo0tho2!sfb&juw2r)
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
      NAME: portoflio
      USER: estphu
      PASSWORD: 12345
      HOST: db
      PORT: 5432
